# Generated by Django 5.2.2 on 2025-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
