# Generated by Django 5.2.2 on 2025-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPPORT', 'Support'), ('USER', 'Customer')], default='SUPPORT', max_length=20),
        ),
    ]
