//define all end point of authentication here
export const authEndpoints = {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    logout: '/auth/logout',
    refreshToken: '/auth/refresh-token',
    me: '/auth/me',
};

//define all endpoints whch are neccesory for the admin panel operations whih one e commerce platform have to perform
export const adminEndpoints = {
    getOrders: '/orders',
    getProducts: '/products',
    getCategories: '/categories',
    getCustomers: '/customers',
    getShipping: '/shipping',
    getPayment: '/payment',
    getReports: '/reports',
    getSettings: '/settings',
    getNotifications: '/notifications',
    getReviews: '/reviews',
    getWishList: '/wish-list',
    getCart: '/cart',
    getOrdersDetails: '/orders/details',
    getProductsDetails: '/products/details',
    getCategoriesDetails: '/categories/details',
    getCustomersDetails: '/customers/details',
    getShippingDetails: '/shipping/details',
    getPaymentDetails: '/payment/details',
    getReportsDetails: '/reports/details',
    getSettingsDetails: '/settings/details',
    getNotificationsDetails: '/notifications/details',
    getReviewsDetails: '/reviews/details',
    getWishListDetails: '/wish-list/details',
    getCartDetails: '/cart/details',
    createOrder: '/orders/create',
    createProduct: '/products/create',
    createCategory: '/categories/create',
    createCustomer: '/customers/create',
    createShipping: '/shipping/create',
    createPayment: '/payment/create',
    createReport: '/reports/create',
    createSettings: '/settings/create',
    createNotification: '/notifications/create',
    createReview: '/reviews/create',
    createWishList: '/wish-list/create',
    createCart: '/cart/create',
    updateOrder: '/orders/update',
    updateProduct: '/products/update',
    updateCategory: '/categories/update',
    updateCustomer: '/customers/update',
    updateShipping: '/shipping/update',
    updatePayment: '/payment/update',
    updateReport: '/reports/update',
    updateSettings: '/settings/update',
    updateNotification: '/notifications/update',
    updateReview: '/reviews/update',
    updateWishList: '/wish-list/update',
    updateCart: '/cart/update',
    deleteOrder: '/orders/delete',
    deleteProduct: '/products/delete',
    deleteCategory: '/categories/delete',
    deleteCustomer: '/customers/delete',
    deleteShipping: '/shipping/delete',
    deletePayment: '/payment/delete',
    deleteReport: '/reports/delete',
    deleteSettings: '/settings/delete',
    deleteNotification: '/notifications/delete',
    deleteReview: '/reviews/delete',
    deleteWishList: '/wish-list/delete',
    deleteCart: '/cart/delete',
}